# 유레카 서버 Port
server:
  port: 8761

spring:
  application:
    name: discovery-service

# eureka 설정 ( Standalone Mode )
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false     # 클라이언트가 자신을 Eureka 서버에 등록할지 여부를 결정. eureka server에 자신을 등록하지 않음. registry에 등록할지 여부. false로 하지 않으면 자기 자신을 클라이언트로 등록함
    fetch-registry: false           # Eureka서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지를 설정. 레지스트리 정보를 로컬에 캐싱하지 않음. registry에 있는 정보들을 가져올지 여부
    service-url:
      #defaultZone: http://localhost:8761/eureka/         # Eureka Server 경로
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/         # Eureka Server 경로 ( defaultZone: http://localhost:8761/eureka/ 와 같은 설정임. )
  server:
    # Self-Preservation : 특정 시간이나 횟수등의 값을 초과하는 heartbeat 를 수신하지 못할때 Eureka 레지스트리에서 해당 인스턴스의 만료를 중지하는 기능
    enable-self-preservation: true   # default

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF