# 유레카 서버 Port
server:
  port: 8761

spring:
  application:
    name: discovery-service

# eureka 설정
eureka:
  client:
    register-with-eureka: false     # 클라이언트가 자신을 Eureka 서버에 등록할지 여부를 결정. eureka server에 자신을 등록하지 않음. registry에 등록할지 여부. false로 하지 않으면 자기 자신을 클라이언트로 등록함
    fetch-registry: false           # Eureka서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지를 설정. 레지스트리 정보를 로컬에 캐싱하지 않음. registry에 있는 정보들을 가져올지 여부
    service-url:
      defaultZone: http://localhost:8761/eureka/         #Eureka Server 명시